ARTIFACTSETKEYS = [
    "Adventurer",
    "ArchaicPetra",
    "Berserker",
    "BlizzardStrayer",
    "BloodstainedChivalry",
    "BraveHeart",
    "CrimsonWitchOfFlames",
    "DeepwoodMemories",
    "DefendersWill",
    "DesertPavilionChronicle",
    "EchoesOfAnOffering",
    "EmblemOfSeveredFate",
    "FlowerOfParadiseLost",
    "FragmentOfHarmonicWhimsy",
    "Gambler",
    "GildedDreams",
    "GladiatorsFinale",
    "GoldenTroupe",
    "HeartOfDepth",
    "HuskOfOpulentDreams",
    "Instructor",
    "Lavawalker",
    "LuckyDog",
    "MaidenBeloved",
    "MarechausseeHunter",
    "MartialArtist",
    "NighttimeWhispersInTheEchoingWoods",
    "NoblesseOblige",
    "NymphsDream",
    "ObsidianCodex",
    "OceanHuedClam",
    "PaleFlame",
    "PrayersForDestiny",
    "PrayersForIllumination",
    "PrayersForWisdom",
    "PrayersToSpringtime",
    "ResolutionOfSojourner",
    "RetracingBolide",
    "Scholar",
    "ScrollOfTheHeroOfCinderCity",
    "ShimenawasReminiscence",
    "SongOfDaysPast",
    "TenacityOfTheMillelith",
    "TheExile",
    "ThunderingFury",
    "Thundersoother",
    "TinyMiracle",
    "TravelingDoctor",
    "UnfinishedReverie",
    "VermillionHereafter",
    "ViridescentVenerer",
    "VourukashasGlow",
    "WanderersTroupe",
]

ARTIFACTSLOTKEYS = [
    "flower",
    "plume",
    "sands",
    "goblet",
    "circlet",
]

artMaxLevel = {
    1: 4,
    2: 4,
    3: 12,
    4: 16,
    5: 20,
}

artifactSandsStatKeys = [
    "hp_",
    "def_",
    "atk_",
    "eleMas",
    "enerRech_",
]

artifactGobletStatKeys = [
    "hp_",
    "def_",
    "atk_",
    "eleMas",
    "physical_dmg_",
    "anemo_dmg_",
    "geo_dmg_",
    "electro_dmg_",
    "hydro_dmg_",
    "pyro_dmg_",
    "cryo_dmg_",
    "dendro_dmg_",
]

artifactCircletStatKeys = [
    "hp_",
    "def_",
    "atk_",
    "eleMas",
    "critRate_",
    "critDMG_",
    "heal_",
]
artSlotMainKeys = {
    "flower": "hp",
    "plume": "atk",
    "sands": artifactSandsStatKeys,
    "goblet": artifactGobletStatKeys,
    "circlet": artifactCircletStatKeys,
}

allMainStatKeys = {
    "HP": "hp",
    "HP_": "hp_",
    "ATK": "atk",
    "ATK_": "atk_",
    "DEF": "def_",
    "DEF_": "def_",
    "Elemental Mastery": "eleMas",
    "Energy Recharge_": "enerRech_",
    "CRIT Rate_": "critRate_",
    "CRIT DMG_": "critDMG_",
    "Physical DMG Bonus_": "physical_dmg_",
    "Anemo DMG Bonus_": "anemo_dmg_",
    "Geo DMG Bonus_": "geo_dmg_",
    "Electro DMG Bonus_": "electro_dmg_",
    "Hydro DMG Bonus_": "hydro_dmg_",
    "Pyro DMG Bonus_": "pyro_dmg_",
    "Cryo DMG Bonus_": "cryo_dmg_",
    "Dendro DMG Bonus_": "dendro_dmg_",
    "Healing Bonus_": "heal_",
}
