allElementKeys = [
    "anemo",
    "geo",
    "electro",
    "hydro",
    "pyro",
    "cryo",
    "dendro",
]
allRegionKeys = [
    "mondstadt",
    "liyue",
    "inazuma",
    "sumeru",
    "fontaine",
    "natlan",
    "snezhnaya",
    "khaenriah",
]

allMoveKeys = [
    "normal",
    "charged",
    "plunging",
    "skill",
    "burst",
    "elemental",
]
characterSpecializedStatKeys = [
    "hp_",
    "atk_",
    "def_",
    "eleMas",
    "enerRech_",
    "heal_",
    "critRate_",
    "critDMG_",
    "physical_dmg_",
    "anemo_dmg_",
    "geo_dmg_",
    "electro_dmg_",
    "hydro_dmg_",
    "pyro_dmg_",
    "cryo_dmg_",
    "dendro_dmg_",
]
nonTravelerCharacterKeys = [
    "Albedo",
    "Alhaitham",
    "Aloy",
    "Amber",
    "AratakiItto",
    "Arlecchino",
    "Baizhu",
    "Barbara",
    "Beidou",
    "Bennett",
    "Candace",
    "Charlotte",
    "Chevreuse",
    "Chiori",
    "Chongyun",
    "Clorinde",
    "Collei",
    "Cyno",
    "Dehya",
    "Diluc",
    "Diona",
    "Dori",
    "Emilie",
    "Eula",
    "Faruzan",
    "Fischl",
    "Freminet",
    "Furina",
    "Gaming",
    "Ganyu",
    "Gorou",
    "HuTao",
    "Jean",
    "Kachina",
    "KaedeharaKazuha",
    "Kaeya",
    "KamisatoAyaka",
    "KamisatoAyato",
    "Kaveh",
    "Keqing",
    "Kinich",
    "Kirara",
    "Klee",
    "KujouSara",
    "KukiShinobu",
    "Layla",
    "Lisa",
    "Lynette",
    "Lyney",
    "Mika",
    "Mona",
    "Mualani",
    "Nahida",
    "Navia",
    "Neuvillette",
    "Nilou",
    "Ningguang",
    "Noelle",
    "Qiqi",
    "RaidenShogun",
    "Razor",
    "Rosaria",
    "SangonomiyaKokomi",
    "Sayu",
    "Sethos",
    "Shenhe",
    "ShikanoinHeizou",
    "Sigewinne",
    "Somnia",
    "Sucrose",
    "Tartaglia",
    "Thoma",
    "Tighnari",
    "Venti",
    "Wanderer",
    "Wriothesley",
    "Xiangling",
    "Xianyun",
    "Xiao",
    "Xingqiu",
    "Xinyan",
    "YaeMiko",
    "Yanfei",
    "Yaoyao",
    "Yelan",
    "Yoimiya",
    "YunJin",
    "Zhongli",
]

travelerElements = [
    "anemo",
    "geo",
    "electro",
    "dendro",
    "hydro",
]

allTravelerKeys = [
    "TravelerAnemo",
    "TravelerGeo",
    "TravelerElectro",
    "TravelerDendro",
    "TravelerHydro",
]

absorbableEle = [
    "hydro",
    "pyro",
    "cryo",
    "electro",
]
allowedAmpReactions = {
    "pyro": ["vaporize", "melt"],
    "hydro": ["vaporize"],
    "cryo": ["melt"],
    "anemo": ["vaporize", "melt"],
}

allowedAdditiveReactions = {
    "dendro": ["spread"],
    "electro": ["aggravate"],
    "anemo": ["aggravate"],
}
